### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by eric-f** [UBC-MDS/DSCI_522_Breast_cancer_predictors#22]
__Mechanics__
- [ ] Could have edited the README from the proposal version more rather than just adding new items to the list. E.g. at the very beginning, you might tell a nice little story about this project and make it inviting to read on.
- [ ] Could have explained more on what are the expected input and output of the scripts. Also, might want to state the dependencies of the scripts, e.g. whose output is whose expected input.
- [ ] In README, might want to add a direct link to final_report.ipynb

__Quality__
- [ ] Documentation missing at the top of `01_read_data.py`
- [ ] In addition to showing an usage example, might want to explain what the arguments are, e.g. input file, output folder, etc...

__Report__
- [ ] Final report should be under the `doc` folder?
- [ ] Need to add an overview of the dataset in Introduction. What are the variables and their definitions? Maybe show some summary statistics too.
- [ ] Figures need a label, a title and ideally a short descriptive caption.
- [ ] Aesthetic-wise, would be nice to replace the snake_case with the usual case throughout.
- [ ] Text in figures are too small to read. Impossible to read the tree diagram.
- [ ] Also, need to explain how to read this tree diagram.
- [ ] Need a section on critique the analysis (limitations, assumptions, etc)
- [ ] Need a statement of future directions. What would you do if you have more time to work on this.
- [ ] You are expected to have a reference section. At least cite the data source.

**Comment by milicmil** [comment]
Hey Arzan, 

I will work on the Readme file to make a nicer introduction (1) as well as fix the .py files to make them more clear as Eric suggested.

**Comment by nazra-inari** [comment]
I agree, We have 4 points pending from the peer feedback and then the rest of Eric's changes. Be sure to tick off the ones you have completed.
